### PR TITLE
bump version for 4.3.0 release

### PR DESCRIPTION
**Pull request by yaauie**

### CODE REVIEW

**Comment by jsvd** [comment]
https://travis-ci.org/logstash-plugins/logstash-input-elasticsearch/jobs/424562534#L1173 looks like a legit failure

**Comment by jsvd** [comment]
for now removing this from jarvis queue unti we understand the reasons for ci failing

**Comment by yaauie** [comment]
One of the failures is definitely a race condition in the rspec mocks that I had _though_ that I had eliminated, but is apparently still present.

I think the other one is too.

I'll see if I can mitigate. Testing concurrency is hard when RSpec isn't threadsafe.

**Comment by yaauie** [comment]
I'm holding off on merging until I can finish chasing down the race condition. I am confident that it exists only in specs (the validation of partial mocks created with `expect(x).to receive(y)...` is not threadsafe), but am adverse to having flaky specs.

**Comment by yaauie** [comment]
Failures here are due to https://github.com/rspec/rspec-mocks/pull/1236 and will remain intermittent until that fix makes its way to a release. I have not found a way to completely eliminate without solving the underlying bug in rspec, so I will continue to chase that down.

**Pull request closed without merging**
