### PR TITLE
fix name for non scan configurations

### PR DESCRIPTION
**Pull request by talevy**

### CODE REVIEW

**Comment by talevy** [comment]
I am also open to having a check whether `resp` exists. and short-circuiting it to avoid error. what do you think @jsvd?

**Comment by jsvd** [comment]
I like reusing the variable, but unless `run_next`returns an hash with strings as keys then this can break.

I don't see a big performance cost here, but if you consider it big enough then wrap the first scroll response into a symbol-keyed hash and we're done.

**Comment by talevy** [comment]
updated to keep same field name

**Comment by jsvd** [comment]
hum..still, without a `@scan` then search response hash won't have a `"has_hits"` key/value

**Comment by jsvd** [comment]
maybe this should have a test? :) clearly there's some fallible logic here

**Comment by jsvd** [comment]
already included in #27

**Pull request closed without merging**
