### PR TITLE
Fix example to have correct configuration key

### PR DESCRIPTION
**Pull request by xelibrion**

### CODE REVIEW

**Comment by talevy** [comment]
Thanks!

**Comment by talevy** [comment]
@xelibrion would you mind signing our CLA, see:
https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

Thanks!

**Comment by xelibrion** [comment]
Done.

**Comment by talevy** [comment]
Thanks, appreciate it!

**Comment by xelibrion** [comment]
No worries!

**Pull request merged**
