### PR TITLE
Added missing quote to docinfo_fields example.

### PR DESCRIPTION
**Pull request by mjpowersjr**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by mjpowersjr** [comment]
Just FYI - I did sign the CLA shortly before submitting the pull request. Regardless, I'm only attempting to contribute a single character. :-)

**Comment by karenzone** [comment]
@mjpowersjr Thanks for signing the CLA and for the contribution.  That "single character" you contributed makes a big difference. It's so important that our docs and examples are correct. Thanks for making them better. 

Also, thanks for being a first-time contributor. Hope to see more contributions from you.

**Review by karenzone — APPROVED** [review]
Builds cleanly and LGTM! Thanks for helping us make our docs better.

**Comment by karenzone** [comment]
Version bump and publish included with #143

**Pull request merged**
